### ISSUE TITLE
Evaluation script for the competition of instance segmentation

### ISSUE THREAD

**Issue by ywyue** [meidachen/STPLS3D#15]
Hi, thanks again for the great work! For instance segmentation, you set up the HAIS baseline and provide the [evaluation script](https://github.com/meidachen/STPLS3D/blob/02c538c256892a46478b8ee2126dca7441a8fd94/HAIS/util/eval.py) to calculate AP. However, this evaluation assumes that we separate the ground truth and predication into individual blocks. For the competition, the evaluation server accepts the submission of a single .predict file for the whole point cloud (e.g. area 26). I wonder could you please also provide the evaluation script used on the evaluation server? Since the output of my current method is the prediction for the whole point cloud instead of individual blocks, I think the evaluation script used on your evaluation server would make the evaluation easier. Thanks in advance!

**Comment by meidachen** [comment]
Hi @ywyue,

The evaluation script is almost the same as the one from HAIS, basically, the whole point cloud will still be split into 50*50m blocks for evaluation. I will upload the script to his repo.

**Comment by ywyue** [comment]
Thanks for the quick response!

**Comment by YellowPuppy** [comment]
> Hi @ywyue,
> 
> The evaluation script is almost the same as the one from HAIS, basically, the whole point cloud will still be split into 50*50m blocks for evaluation. The script is uploaded to the HAIS folder.

How to use the script STPLS3DInstanceSegmentationChallenge_Codalab_Evaluate.py? Thank you!
