### ISSUE TITLE
How to inference in the test set of stpls3d dataset?

### ISSUE THREAD

**Issue by YellowPuppy** [meidachen/STPLS3D#20]
How to infer in the test set of stpls3d? In other words, is there an inference script for unlabeled data in stpls3d (i.e. 26_points_gtv3.txt, 27_points_gtv3.txt, 28_points_gtv3.txt)?

**Comment by meidachen** [comment]
Sorry, but we don't provide such a script.

**Comment by meidachen** [comment]
@YellowPuppy , I just updated the instruction on HAIS on the main page, please take a look, it now contains the steps for inference for unlabeled data in stpls3d

**Comment by YellowPuppy** [comment]
Thank you so much!
