### ISSUE TITLE
instance label 0 mean

### ISSUE THREAD

**Issue by Wangcongyu620** [meidachen/STPLS3D#22]
Hi, @meidachen 
Thank you for sharing a new interesting outdoor dataset for instance segmentation first. I have a little problem that I haven't understood for a long time. For HAIS instance result , if the instance label equal to 0，What does it mean? I found that the instance label 0 appeared in different blocks. I'm confused. Look forward to your reply！

**Comment by meidachen** [comment]
Hi @Wangcongyu620 ,

Thanks for your interest in our dataset. Instance labeled 0 should be ground I think, as can be seen here:

https://github.com/meidachen/STPLS3D/blob/65917491c6a507b97c1d1ed60dcffd418524e3d8/HAIS/util/utils_3d.py#L64

label 0 is ignored during evaluation.

**Comment by Wangcongyu620** [comment]
Thank you for your reply. I understand you,bur I think Instance label 0 should not represent ground.Because its semantic label is not equal to 0 .  Now I'm testing my own data.
![test](https://user-images.githubusercontent.com/72800720/181668431-193044b9-403e-4b87-9a94-e4a55df2ac92.jpg)
Semantic label equal to 4 means high vegetation, but the instance label 0,This made my result very bad. When I remove the dot labeled 0, the result is acceptable. So I want to know what the instance label 0 means.
**Show only the overall results of vegetation**
![3d2db9ad886cfb559a47779ebb531cb](https://user-images.githubusercontent.com/72800720/181669313-fed42475-88c6-4db1-8677-831cd6e79d99.jpg)
**Result of removing tag 0**
![5a1b6cc0d68f8f714367ce57b715429](https://user-images.githubusercontent.com/72800720/181669489-aa84792d-6247-4529-874e-766b8a8c6088.jpg)
It is obvious that all green represents the 0 label，In this code, I can't find what the prediction of 0 means.
Sorry to disturb you again, looking forward to your reply!

**Comment by Wangcongyu620** [comment]
@Lizhinwafu I also use cloudcompare , just for visualization.

**Comment by Wangcongyu620** [comment]
My dataset is similar. I understand you！So？

**Comment by Wangcongyu620** [comment]
OK. add you

**Comment by meidachen** [comment]
@Wangcongyu620 ,

I'm not so sure about what's going on with your data. But one thing I can think of is that instance and semantic labels are merged during evaluation (i.e., semantic*1000 + instance) this is what I was trying to refer to, but not "instance 0". If you haven't thought about this, this may give you a hint, hopefully. Also, I saw in your result, that it seems like the ground was miss segmented as semantic 4 (high veg), and a lot of these grounds were then labeled as instance 0. Not sure, if this is related to ignoring some semantic labels during training. 

Sorry, I can't give you a direct answer but only try to help based on my limited knowledge.

**Comment by Wangcongyu620** [comment]
I understand. Thank you for your patient answer. Thank you

**Comment by Greatest-Marx** [comment]
> Hi, @meidachen Thank you for sharing a new interesting outdoor dataset for instance segmentation first. I have a little problem that I haven't understood for a long time. For HAIS instance result , if the instance label equal to 0，What does it mean? I found that the instance label 0 appeared in different blocks. I'm confused. Look forward to your reply！
Hello! May I ask if you have solved this problem? I am also making my own dataset and am testing it with HAIS, would appreciate if you could get back to me!

**Comment by Greatest-Marx** [comment]
> Can you add QQ to discuss it? [2479929042@qq.com](mailto:2479929042@qq.com)

Hello! I am a second year student at China University of Geosciences, I am also training HAIS with my own dataset, may I add your QQ?
