### ISSUE TITLE
I want to make my own dataset

### ISSUE THREAD

**Issue by Lizhinwafu** [meidachen/STPLS3D#23]
I have apple tree point cloud dataset with two semantic classes trunk, branch. One line of my annotation data is as follows.
0.013332,  0.111240,  1.698000,112.000000,109.000000,102.000000,  0.000000,  0.000000

There are 8 columns in total：x,y,z,R,G,B, semantic label(trunk is 0/branch is 1), instance label(trunk is 0, branch1 is 1,branch2 is 2,...).
I'm not sure if this is right and need your help. I use CloudCompare for annotation.

Many thanks.

**Comment by meidachen** [comment]
That is how I usually annotate my data. Just make sure you understand which semantic label will be ignored when training and testing the model. For instance, in STPLS3D ground is labeled as 0, and will not be evaluated.

**Comment by meidachen** [comment]
I used -100 as the instance label for all the ground points that have the semantic label of 0 in STPLS3D. I believe you could use -100 as the instance label for the trunk points in your data.

**Comment by Greatest-Marx** [comment]
> I have apple tree point cloud dataset with two semantic classes trunk, branch. One line of my annotation data is as follows. 0.013332, 0.111240, 1.698000,112.000000,109.000000,102.000000, 0.000000, 0.000000
> 
> There are 8 columns in total：x,y,z,R,G,B, semantic label(trunk is 0/branch is 1), instance label(trunk is 0, branch1 is 1,branch2 is 2,...). I'm not sure if this is right and need your help. I use CloudCompare for annotation.
> 
> Many thanks.
Hello, have you already made your own label and trained it successfully?

**Comment by LinLin1031** [comment]
> I used -100 as the instance label for all the ground points that have the semantic label of 0 in STPLS3D. I believe you could use -100 as the instance label for the trunk points in your data.

But what if I want to evaluate both classes? @meidachen @Greatest-Marx @Lizhinwafu

**Comment by Greatest-Marx** [comment]
> > I used -100 as the instance label for all the ground points that have the semantic label of 0 in STPLS3D. I believe you could use -100 as the instance label for the trunk points in your data.
> 
> But what if I want to evaluate both classes? @meidachen @Greatest-Marx @Lizhinwafu

你的意思是你既想评估实例标签为-100的对象，又想评估标签为1的对象？

**Comment by hplegend** [comment]
I encounter same problem.  Following  first imge is sematic predicate result, however, instance predicate result as seconed image show can't identity truck.
![image](https://github.com/user-attachments/assets/810ddcbf-ed18-4bce-92a7-213afee6c820)
![image](https://github.com/user-attachments/assets/97b8d907-a7b0-423e-958e-d1e255770449)

I want to realize instance segmentation  and sematic segmentation, how can i modify config?
