### ISSUE TITLE
Results visualization

### ISSUE THREAD

**Issue by Ritchizh** [meidachen/STPLS3D#3]
Hi! Sorry for bothering you again)
Considering **mergeResults.py** -- do you form test folder manually?

I manually placed into test 100 results files from _exp/Synthetic_v3_InstanceSegmentation/hais/hais_run_stpls3d/result/val/_ , related to one area (? as I assumed) with index 5 (for example, files **5**_points_GTv3_**00**_inst_nostuff.npy ... **5**_points_GTv3_**99**_inst_nostuff.npy from _coords_offsets_, and corresponding files from _semantic_ and _predicted_masks_).
As _test/coordShift.json_ I took _coordShift.json_ file from  _dataset/Synthetic_v3_InstanceSegmentation/val/_.
The resulting point cloud _out.txt_ visualized in CloudCompare:

![pcl5](https://user-images.githubusercontent.com/18049634/171141815-6479167d-8bc3-4f49-bc8e-5876bb0fe126.jpg)

It looks like some shift values are wrong. Could you possibly tell how to fix it?

**Comment by meidachen** [comment]
Not a problem, please set the last parameter to False at:

https://github.com/meidachen/STPLS3D/blob/453103c14761d11eece09bc073699c0cb2e8344c/HAIS/data/stpls3d_inst.py#L292

https://github.com/meidachen/STPLS3D/blob/453103c14761d11eece09bc073699c0cb2e8344c/HAIS/data/stpls3d_inst.py#L371

Please let me know if this fixed your problem.

**Comment by Ritchizh** [comment]
It worked, thank you!
