### ISSUE TITLE
KPConv-STPLS3D- Data Problem

### ISSUE THREAD

**Issue by zhangbaobao1027** [meidachen/STPLS3D#31]
first of all thanks.
I use KPConv and STPLS3D dataset for training，
When the training progresses to epoch130, an error will appear:
'It seems this dataset only containes empty input spheres'

Currently I skip these abnormal epochs, is it a data problem, and is there a better solution?
part of the code：

            # Number collected
            n = input_inds.shape[0]

            # Safe check for empty spheres  
            if n < 2:
                failed_attempts += 1
                if failed_attempts > 100 * self.config.batch_num:
                    # raise ValueError('It seems this dataset only containes empty input spheres')
                    print('It seems this dataset only containes empty input spheres')
                    return []
                t += [time.time()]
                t += [time.time()]
                continue

            # Collect labels and colors
            input_points = (points[input_inds] - center_point).astype(np.float32)

**Comment by meidachen** [comment]
@zhangbaobao1027 , Really sorry for the late reply, It seems like the point density and the sphere radius make it empty sometimes. I believe this should work fine, but just to make sure the density of the points and the radius are making sense.

**Comment by zhangbaobao1027** [comment]
Thank you very much, it's real a data problem.
